name: Image Builds
on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        image-name:
          - ghcr.io/ThinkChaos/transmission-openvpn
        include:
          - image-name: ghcr.io/ThinkChaos/transmission-openvpn
            context: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # QEMU emulator to build for other platforms
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Buildx automates creating the multi-arch manifest build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Authenticate so that we can push to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate image tags and labels
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ matrix.image-name }}
          tags: |
            type=edge
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      # Finally, build and push the images
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          platforms: linux/arm
          build-args: |
            REVISION=${{ github.sha }}
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: haugene/transmission-openvpn
          cache-to: type=gha, scope=${{ github.workflow}}
